routes/web.php
			Route::get('/delete/', 'adminController@deleteBootcamp')->name('bootcamp.delete');
			Route::get('/applicant', 'adminController@eventlist')->name('eventlist');
			Route::get('/applicant/{id}', 'adminController@applicant')->name('applicant.index');
			Route::get('/allapplicant/', 'adminController@allApplicant')->name('applicant.all');
			Route::get('/alllolos/', 'adminController@allLolos')->name('applicant.lolos');
			Route::get('/allsend/', 'adminController@allSend')->name('applicant.send');
			Route::get('/allrecruit/', 'adminController@allRec')->name('applicant.rec');
			Route::post('/addapplicant', 'adminController@storeApplicant')->name('applicant.store');
			Route::get('/editapplicant/{id}', 'adminController@editApplicant')->name('applicant.edit');
			Route::put('/updateapplicant/{id}', 'adminController@updateApplicant')->name('applicant.update');
			Route::get('/deleteapplicant/', 'adminController@deleteApplicant')->name('applicant.delete');
			Route::get('/move/lolos', 'adminController@move')->name('applicant.movelolos');
			Route::get('/move/recruit', 'adminController@moverec')->name('applicant.moverec');
			Route::get('/move/send', 'adminController@movesend')->name('applicant.movesend');
			Route::post('/link/add', 'adminController@linkAdd')->name('link.add');
			// Route::post('/link/remove', 'jobsapplyController@noteRemove')->name('link.remove');
			Route::post('/link/get', 'adminController@linkGet')->name('link.get');
		});
		Route::group(['prefix'=>'campaign'], function(){
			Route::get('/', 'CampaignController@index')->name('campaign.index');
			Route::get('/all', 'CampaignController@all')->name('campaign.all');
			Route::get('/assign', 'CampaignController@assign')->name('campaign.assign');
			Route::post('/delete', 'CampaignController@delete')->name('campaign.delete');
			Route::get('/getmedia', 'CampaignController@getMedia')->name('campaign.getmedia');
			Route::post('/mediachecked', 'CampaignController@mediaChecked')->name('campaign.mediachecked');
			Route::get('/getjobs', 'CampaignController@getJobs')->name('campaign.getjobs');
			Route::post('/jobschecked', 'CampaignController@jobsChecked')->name('campaign.jobschecked');
			Route::post('/checked', 'CampaignController@checked')->name('campaign.checked');
			Route::post('/unchecked', 'CampaignController@unchecked')->name('campaign.unchecked');
			Route::post('/jobs_checked', 'CampaignController@jobs_checked')->name('campaign.jobs_checked');
			Route::post('/jobs_unchecked', 'CampaignController@jobs_unchecked')->name('campaign.jobs_unchecked');
		});

		Route::resource('companies','CompaniesController');
		Route::post('/companies/getdetail','CompaniesController@getdetail')->name('companies.getdetail');
		Route::get('/companies/request/{id}','CompaniesController@request')->name('companies.request');
		Route::post('/companies/addreq', 'CompaniesController@addReq')->name('companies.addReq');
		Route::post('/companies/addreq2', 'CompaniesController@addReq2')->name('companies.addReq2');
		Route::post('/companies/getreq', 'CompaniesController@getReq')->name('companies.getReq');
		Route::delete('/companies/delreq/{id}','CompaniesController@delReq')->name('companies.delReq');
		Route::post('/editreq', 'CompaniesController@editReq')->name('companies.editReq');
		Route::post('/editreq2', 'CompaniesController@editReq2')->name('companies.editReq2');
		Route::get('/companyassign','CompaniesController@companyassign')->name('companies.assign');
		Route::get('/companyassign/{id}','CompaniesController@companyassign')->name('companies.assign');
		Route::get('/companyassign/allassign/','CompaniesController@allassign')->name('companies.dataassign');
		Route::get('/companyrequest','CompaniesController@companyrequest')->name('companies.companyrequest');
		Route::get('/companyrequest/datarequest','CompaniesController@datarequest')->name('companies.datarequest');


		Route::group(['prefix'=>'company'], function(){
			Route::get('/', 'companyController@index')->name('company.index');
			Route::get('/request/{id}', 'companyController@request')->name('company.request');
			Route::get('/all', 'companyController@all')->name('company.all');
			Route::get('/detail/{id}','companyController@detail')->name('company.detail');
			Route::get('/edit', 'companyController@edit')->name('company.edit');
			Route::post('/update/{id}', 'companyController@update');
			Route::get('/allrequest', 'companyController@allRequest')->name('company.allrequest');
			Route::get('/requestttt','companyController@Requesttest')->name('company.requesttest');
			Route::post('/add', 'companyController@add')->name('company.add');
			Route::post('/addreq', 'companyController@addReq')->name('company.addReq');
			Route::post('/editreq', 'companyController@editReq')->name('company.editReq');
			Route::post('/getreq', 'companyController@getReq')->name('company.getReq');
		});

		Route::group(['prefix'=>'talent'], function(){

			
			// adi
			Route::get('/list','TalentNewController@show')->name('talent.list');
			Route::get('/list/condition','TalentNewController@condition');
			Route::get('/list/search','TalentNewController@search');
			Route::get('/list/filter','TalentNewController@filter');
			Route::get('/list/paginate_data','TalentNewController@paginate_data');
			//end adi


			Route::get('/', 'talentController@index')->name('talent.index');

			//Route Talent List
	// 		Route::get('/', 'talentController@talent_list')->name('talent.listall');
			// Route::get('/request', 'companyController@request')->name('talent.request');
			Route::get('/all', 'talentController@all')->name('talent.all');
			Route::get('/edit', 'talentController@edit')->name('talent.edit');
			// Route::post('/update/{id}', 'talentController@update');
			Route::post('/add', 'talentController@add')->name('talent.add');
			Route::post('/update/{id}', 'talentController@update');
			Route::get('/talentskill/{id}', 'talentController@talentskill')->name('talent.talentskill');
	        Route::get('/portfolio', 'talentController@portfolio')->name('portfolio.talent');
	        Route::get('/portfolio-delete', 'talentController@portfolioDelete')->name('portfolio.delete');
	        Route::post('/portfolio-update','talentController@portfolioUpdate')->name('portfolio.update');
	        Route::post('/portfolio-insert', 'talentController@portfolioInsert')->name('portfolio.insert');

	        Route::get('/workexperience','talentController@workex')->name('workex.talent');
	        Route::post('/workexperience-insert','talentController@workexInsert')->name('workex.insert');
	        Route::post('/worexperience-update','talentController@workexupdate')->name('workex.update');
	        Route::get('/workexdetail/{id}','talentController@workexdetail')->name('workex.detail');
	        Route::get('/workex-delete','talentController@workex_delete')->name('workex.delete2');
	        Route::post('/workexdelete/{id}','talentController@workexdelete')->name('workex.delete');

	        Route::resource('pratalent', 'PratalentController');
			Route::get('/pratalent/datalinkedin','PratalentController@datalinkedin')->name('pratalent.datalinkedin');
			Route::post('/pratalent/import','PratalentController@import_excel')->name('pratalent.import');
			Route::post('/pratalent/changestatus','PratalentController@changeStatus')->name('pratalent.changestatus');
			

	        Route::post('/addeducation','talentController@addeducation')->name('education.add');
	        Route::get('/detaileducation/{id}','talentController@detaileducation')->name('education.detail');
	        Route::post('/updateeducation/{id}','talentController@updateeducation')->name('education.update');
	        Route::post('/deleteeducation/{id}','talentController@deleteeducation')->name('education.delete');

	        Route::post('/addcertification', 'talentController@addcertification')->name('certification.add');
	        Route::get('/detailcertification/{id}','talentController@detailcertification')->name('certification.detail');
	        Route::post('/updatecertification/{id}','talentController@updatecertification')->name('certification.update');
	        Route::post('/deletecertification/{id}','talentController@deletecertification')->name('certification.delete');

			Route::get('/detailtalent/{id}','talentController@detailtalent')->name('detailtalent');
	        Route::post('/notesreporttalent/{id}','talentController@storenote')->name('notesreporttalent');
	        Route::get('/viewcertif/{id}','talentController@viewcertif')->name('viewcertif');
	        Route::get('/vieweducation/{id}','talentController@viewedu')->name('viewedu');
	        Route::post('/previewreporttalent','ReportTalentPDF@generatePdf')->name('downloadreporttalentnya');

	        Route::get('/all/unprocess', 'talentController@allUnprocess')->name('talent.unprocess');
			Route::get('/all/quarantine', 'talentController@allQuarantine')->name('talent.allquarantine');
			Route::get('/all/assign', 'talentController@allAssign')->name('talent.assign');
			Route::post('/changestatus', 'talentController@changeStatusAssign')->name('talent.changestatus');
			Route::post('/changestatusassign', 'talentController@changeStatus')->name('talent.changestatusassign');
			Route::post('/changestatusquarantine', 'talentController@changeStatusQuarantine')->name('talent.changestatusquarantine');
			Route::get('/detail', 'talentController@detail')->name('talent.detail');
			// Route::get('/detail/{id}', 'talentController@detail')->name('talent.detail');
			Route::get('/delete', 'talentController@delete')->name('talent.delete');
			Route::get('/move', 'talentController@move')->name('talent.move');
			Route::get('/skill', 'talentController@skillTalent')->name('talent.skill');
			Route::get('/deleteskill','talentController@deleteskill')->name('talent.deleteskill');
			Route::post('/addskill', 'talentController@addSkillTalent')->name('talent.addskill');
			Route::post('/addsapply', 'talentController@addApplyTalent')->name('talent.addapply');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
	protected $table      = 'company';
	protected $primaryKey = 'company_id';
	protected $fillable   = ['company_name', 'company_email', 'company_phone'];
	public $timestamps    = false;

}

app/Http/Controllers/companyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Yajra\Datatables\Datatables;
use App\Models\Company;
use App\Models\Requestt;
use Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Hash;


class companyController extends Controller
{

  public function __construct()
  {
    if(session('level') != 'admin') {
      Auth::logout();
      return redirect('/');
    }
      $this->middleware('auth');
  }

  public function index()
  {
    $company = DB::table('company')->orderBy('company_name', 'asc')->get();
    $skill = DB::table('skill')->get();
    $jobs = DB::table('jobs')->get();
    return view('admin.company.list',compact('skill','jobs','company'));
  }

  public function request($id)
  {
    $a =DB::table('company')->where('company_id',$id)->get();
    $all = DB::table('request')->join('company','request_company_id','company_id')->where('request_company_id',$id)->get();
    return view('admin.company.request',compact('all','a'));
  }

  public function detail($id)
  {

    $all=DB::table('company')->where('company_id',$id)->get();
    return view('admin.company.detailcompany',compact('all'));

  }

  public function all()
  {
    $all = DB::table('company')->orderBy('company_name', 'asc')->get();
    return Datatables::of($all)
      ->addIndexColumn()
      ->addColumn('category_name', function($all){
        return $all->company_name ;
      })
      ->addColumn('category_address', function($all){
        return $all->company_address ;
      })
      ->addColumn('category_email', function($all){
        return $all->company_email ;
      })
      ->addColumn('category_phone', function($all){
        return $all->company_phone ;
      })
      ->addColumn('qty', function($all){
        $qty = DB::table('request')->where([['request_company_id', '=', $all->company_id], ['request_status', '!=', 'done']])->count();
        return $qty ;
      })
      ->addColumn('action', function($all){
        return '<center>
        <a href="'.route('company.detail',$all->company_id).'" type="button" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i></a>&nbsp;
        <a href="#" data-toggle="modal" data-target="#requestAdd" data-id="'.$all->company_id.'" data-name="'.$all->company_name.'" type="button" class="btn btn-success btn-xs addReq"><i class="fa fa-list-alt"></i></a>&nbsp;
        <a href="'.route('company.request',$all->company_id).'" type="button" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i></a>&nbsp;
        <a href="'.route('company.request',$all->company_id).'" type="button" class="btn btn-warning btn-xs"><i class="fa fa-edit"></i></a></center>';
      })
      ->rawColumns(['category_name', 'action', 'category_address', 'category_email', 'category_phone', 'qty'])
      ->make(true);
  }

  public function allRequest()
  {
    $all = DB::table('request')->orderBy('request_name', 'asc')->get();
    return Datatables::of($all)
      ->addIndexColumn()
      ->addColumn('company_name', function($all){
        $company = DB::table('company')->select('company_name')->where('company_id', $all->request_company_id)->first();
        return $company->company_name ;
      })
      ->addColumn('request_name', function($all){
        return $all->request_name ;
      })
      ->addColumn('request_qty', function($all){
        return $all->request_qty ;
      })
      ->addColumn('request_location', function($all){
        return $all->request_location ;
      })
      ->addColumn('request_long', function($all){
        return $all->request_long ;
      })
      ->addColumn('request_date', function($all){
        return $all->request_date ;
      })
      ->addColumn('request_status', function($all){
        if($all->request_status=='active') {
          return '<span class"badge badge-success">'.ucfirst($all->request_status).'</span>';
        } elseif($all->request_status=='done') {
          return '<span class"badge badge-default">'.ucfirst($all->request_status).'</span>';
        } else {
          return '<span class"badge badge-warning">'.ucfirst($all->request_status).'</span>';
        }
      })
      ->addColumn('action', function($all){
        $company = DB::table('company')->select('company_name')->where('company_id', $all->request_company_id)->first()->company_name;
        return '<center>
        <a href="#" data-id="'.$all->request_id.'" data-comp="'.$company.'" type="button" class="btn btn-primary btn-xs detail-req"><i class="fa fa-eye"></i></a>&nbsp;<a href="#" data-id="'.$all->request_id.'" type="button" class="btn btn-warning btn-xs edit-req"><i class="fa fa-edit"></i></a></center>';
      })
      ->rawColumns(['company_name', 'action', 'request_name', 'request_status', 'request_qty', 'request_date', 'request_long', 'request_location', 'request_qty'])
      ->make(true);

  }

  public function Requesttest(Request $request)
  {
    return view('admin.company.requesttest');
  }

  public function add(Request $request)
  {
    $data                      = new Company();
    $data->company_name        = $request->input('com-name');
    $data->company_username    = $request->input('com-username');
    $data->company_password    = hash::make($request->com_password);
    $data->company_pic         = $request->input('com-pic');
    $data->company_address     = $request->input('com-address');
    $data->company_description = $request->input('com-desc');
    $data->company_email       = $request->input('com-email');
    $data->company_phone       = $request->input('com-phone');
    $data->save();
    return redirect(route('company.index'))->with(['success' => 'Company successfully added.']);
  }

  public function editReq(Request $request)
  {
    $all = DB::table('request')->where('request_id', $request->input('request_id'))->first();
    echo json_encode($all);
  }

  public function getReq(Request $request)
  {
    $all = DB::table('request')->where('request_id', $request->input('request_id'))->first();
    echo json_encode($all);
  }

  public function addReq(Request $request)
  {
    // dd($request->all());
    $skill = $request->input('skill');
    $data                     = new Requestt();
    $data->request_name       = $request->input('name');
    $data->request_company_id = $request->input('company_id');
    $data->request_detail     = $request->input('detail');
    $data->request_date       = $request->input('start-date');
    $data->request_long       = $request->input('long');
    $data->request_qty        = $request->input('qty');
    $data->request_status     = $request->input('status');
    $data->request_location   = $request->input('location');
    $data->save();
    foreach ($skill as $s){
        $simpan = DB::table('company_position')->insert([
            'cp_request_id'=>$data->request_id,
            'cp_company_id'=>$request->input('company_id'),
            'cp_skill_id'=>$s,
            'cp_jobs_id'=>$request->input('posisi')
        ]);
    }
    return redirect(route('company.index'))->with(['success' => 'Request successfully added.']);
  }


}

resources/views/admin/companies/companyassign.blade.php
@extends('admin.layout.apps')

@section('content')
<style>
    .btn-xs {
        padding: 0.1rem 0.25rem;
        font-size: 0.875rem;
        line-height: 1.3;
        border-radius: 0.2rem !important;
        -webkit-appearance:unset !important;
    }
</style>

<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h3>Company Assign</h3>
                @foreach($a as $company) 
                <strong class="text-muted" style="text-transform: capitalize;">{{$company->company_name}}</strong>
               @endforeach
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="{{route('dashboard')}}">Dashboard</a></li>
                    <li><a href="{{route('companies.index')}}">Company</a></li>
                    <li class="active">Assign</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">
            <div class="action-table">
                <div class="col-md-12 form-inline">
                    <div class="form-group">
                        <div class="col">
                        </div>
                    </div>
                </div>
                    
            </div>

            <div class="col-md-12">

                <div class="card">
                    <div class="card-body">
                        <div class="tab-content">
                            <div class="tab-pane fade show active">
                                <table id="assign-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Talent name</th>
                                            <th>Position</th>
                                            <th>Prefered  Location</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($all as $item2)
                                        <tr>
                                            <td>{{$noassign++}}</td>
                                            <td>{{$item2->talent_name}}</td>
                                            <td>{{$item2->jobs_title}}</td>
                                            <td>{{$item2->location_name}}</td>
                                            <td>
                                            @php
                                            if($item2->assign_status=='review_rt') { $status_text = '2. Review RT'; $status_color='info'; }
                                            elseif($item2->assign_status=='interviewing') { $status_text = '3. Interviewing'; $status_color='success'; }
                                            elseif($item2->assign_status=='report_interview') { $status_text = '4. Report Interview'; $status_color='success'; }
                                            elseif($item2->assign_status=='offering') { $status_text = '5.a. Offering'; $status_color='dark'; }
                                            elseif($item2->assign_status=='hired') { $status_text = '5.b. Hired'; $status_color='primary'; }
                                            elseif($item2->assign_status=='reject') { $status_text = '5.c. Rejected'; $status_color='danger'; }
                                            elseif($item2->assign_status=='cancel') { $status_text = '5.d. Cancelled'; $status_color='secondary'; }
                                            else { $status_text = '1. Send RT'; $status_color='light'; }

                                            if(strlen(strip_tags($item2->assign_desc))>40){ $status_desc = substr(strip_tags($item2->assign_desc), 0,40).'...'; }
                                            else{ $status_desc = strip_tags($item2->assign_desc); }
                                            @endphp
                                            <a href="#change-status" data-id="{{$item2->assign_request_id}}" data-toggle="modal" data-target="#modal-status" type="button" class="btn btn-{{$status_color}} btn-xs change-status" data-placement="top">{{$status_text}}</a>&nbsp;&nbsp;{{substr($item2->assign_status_date, 0,10)}}<br><span title="{{strip_tags($item2->assign_desc)}}">{{$status_desc}}</span>
                                            </td>
                                            <td>
                                            <center>
                                            <a href="" type="button" data-toggle="modal" data-target="#modal-tambah-catatan" type="button" class="btn btn-info btn-xs" data-toggle="tooltip" data-placement="top" title="See Application Details" target="_blank"><i class="fa fa fa-pencil-square-o"></i></a></center>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="modal-status" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-md" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="judul-panjang">Status Assign Talent</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{route('talent.changestatusassign')}}" method="post" accept-charset="utf-8">
        {{ csrf_field() }}
            <div class="modal-body substeps-modal">
                <input type="hidden" name="assign_id" id="assign_id" value="">
                <div class="input-group mb-3">
                    <div class="input-group-prepend "><div class="input-group-text "><input type="radio" name="status" value="send_rt"></div></div>
                    <input type="text" class="form-control" value="1. Send Report Talent" readonly="">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend "><div class="input-group-text "><input type="radio" name="status" value="review_rt"></div></div>
                    <input type="text" class="form-control" value="2. Review Report Talent" readonly="">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend "><div class="input-group-text "><input type="radio" name="status" value="interviewing"></div></div>
                    <input type="text" class="form-control" value="3. Interviewing" readonly="">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend "><div class="input-group-text "><input type="radio" name="status" value="report_interview"></div></div>
                    <input type="text" class="form-control" value="4. Report Interview" readonly="">
                </div>
                <hr>
                <div class="input-group mb-3">
                    <div class="input-group-prepend "><div class="input-group-text "><input type="radio" name="status" value="offering"></div></div>
                    <input type="text" class="form-control" value="5.a. Offering" readonly="">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend "><div class="input-group-text "><input type="radio" name="status" value="hired"></div></div>
                    <input type="text" class="form-control" value="5.b. Hired" readonly="">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend "><div class="input-group-text "><input type="radio" name="status" value="reject"></div></div>
                    <input type="text" class="form-control" value="5.c. Reject" readonly="">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend "><div class="input-group-text "><input type="radio" name="status" value="cancel"></div></div>
                    <input type="text" class="form-control" value="5.d. Cancelled" readonly="">
                </div>
                <hr>
                <div class="input-group">
                    <div class="input-group-prepend "><div class="input-group-text ">Note</div></div>
                    <input type="text" class="form-control" name="note">
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" id='submit-status1' class="btn btn-success" data-dismiss="">Submit</button>
            </div>
        </form>
      </div>
    </div>

</div>

<!-- /#right-panel -->

<!-- /.row -->

<!-- /.container-fluid -->
@push('script')
<script type="text/javascript">

$(document).ready(function() {
    $('#assign-table').DataTable();
});


// $(document).ready(function(){
//     all_table;
// });
// function reload(){
//     all_table.ajax.reload();
// }

// var all_table = $('#assign-table').DataTable({
//         autoWidth:false,
//         filter:true,
//         info:false,
//         paging:true,
//         processing:false,
//         ajax:{
//             url:"{{route('companies.dataassign')}}",
//             type:"GET"
//         },
//         columns:[
//         {data:"talent_name",defaultColumn:"-",visible:true},
//         {data:"jobs_title",defaultColumn:"-",visible:true},
//         {data:"location_name",defaultColumn:"-",visible:true},
//         {data:"assign_status",defaultColumn:"-",visible:true},
//         // {data:"action",orderable:false,searchable:false},
//         ]
// });

$(document).on('click', '.change-status', function() {
    var id   = $(this).data('id');
    $('.modal-body #assign_id').val(id);
});

</script>
@endpush

@endsection